### ISSUE TITLE
when launching the regular 3dsensor.launch with registration on the laserscan is all nans

### ISSUE THREAD

**Issue by mmwise** [turtlebot/turtlebot#57] opened 2013-02-26 06:46 UTC
I noticed this while trying to get a friends turtlebot working. When I launch the follower.launch everything works and when launching 3dsensor.launch all nans. So i went in and changed the parameters to the launch file to be the same as the follower.launch and now the scan is normal and working .. Something seems to be up with the depth_registered being turned on and getting a point cloud out.

**Comment by corot** [comment] 2013-02-26 07:13
I cannot reproduce the problem. Both standalone 3dsensor.launch and follower.launch work fine for me.
depth_registered is set as true by default, but is should be irrelevant for depth_image_to_laserscan.
Are you using debian packages or sources?

**Comment by abencz** [comment] 2013-02-26 15:22
I ran into this too a few days ago. There's a post on ROS answers as well:
http://answers.ros.org/question/53706/registered-depth-image-is-black/#53832

Compiling OpenNi from source as suggested in that thread fixed it.

**Comment by LucidOne** [comment] 2013-02-26 15:34
On 02/26/2013 01:46 AM, Melonee Wise wrote:

> I noticed this while trying to get a friends turtlebot working. When I launch the follower.launch everything works and when launching 3dsensor.launch all nans. So i went in and changed the parameters to the launch file to be the same as the follower.launch and now the scan is normal and working .. Something seems to be up with the depth_registered being turned on and getting a point cloud out.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/turtlebot/turtlebot/issues/57

Is this related to this issue?
https://github.com/turtlebot/turtlebot/issues/55

**Comment by abencz** [comment] 2013-02-26 15:36
I don't think so.

The issue is not that there is no depth_registered data being produced but that the data is all zeros or NaNs.

**Comment by stonier** [comment] 2013-02-27 07:17
Going to need some more information here I think because it works for me too. Versions etc. 

I've installed:
- libopenni-dev, openni-utils 1.5.4.0-3
- libopenni-sensor-primesense-dev 5.1.0.41-2
- libopenni-nite-dev 1.3.1.5
- ros debs from ros-shadow-fixed 26th Feb.
- Kobuki and Turtlebot [sources](http://ros.org/wiki/turtlebot/Tutorials/groovy/Source%20Installation) (these should match the current debs in ros-shadow-fixed).

I'm running in different shells:

```
> roslaunch turtlebot_bringup minimal.launch
> roslaunch turtlebot_bringup 3dsensor.launch
> roslaunch turtlebot_rviz_launchers view_robot.launch
```

And in rviz, I can enable and view the depth registered 3d image, the point cloud registered image and also the laser scan.

**Comment by mmwise** [comment] 2013-02-27 08:02
I updated the laptop to the latest in debs for turtlebot thru apt-get on
feb 25. I could not get any pointcloud to display or laserscan in rviz when
i did a rostopic echo on /scan all i got was Nan.

libopenni-dev/precise uptodate 1.5.4.0-3+precise1
libopenni-sensor-primesense-dev/precise uptodate 5.1.0.41-2+precise1
libopenni-sensor-primesense0/precise uptodate 5.1.0.41-2+precise1
libopenni0/precise uptodate 1.5.4.0-3+precise1

ros-groovy-openni-camera/precise uptodate 1.8.8-0precise-20130129-0900-+0000
ros-groovy-openni-launch/precise uptodate 1.8.3-0precise-20130205-2131-+0000

ros-groovy-turtlebot/precise uptodate 1.9.4-s1360121257~precise
ros-groovy-turtlebot-apps/precise uptodate 1.9.2-s1360294363~precise
ros-groovy-turtlebot-create/precise uptodate 1.9.1-s1359159592~precise
ros-groovy-turtlebot-create-desktop/precise uptodate
1.9.0-s1360094360~precise
ros-groovy-turtlebot-dashboard/precise uptodate 0.1.0-s1360094116~precise
ros-groovy-turtlebot-simulator/precise uptodate 1.9.1-s1360104794~precise
ros-groovy-turtlebot-viz/precise uptodate 1.9.3-s1360275921~precise

On Tue, Feb 26, 2013 at 11:17 PM, Daniel Stonier
notifications@github.comwrote:

> Going to need some more information here I think because it works for me
> too. Versions etc.
> 
> I've installed:
> - libopenni-dev, openni-utils 1.5.4.0-3
> - libopenni-sensor-primesense-dev 5.1.0.41-2
> - libopenni-nite-dev 1.3.1.5
> - ros debs from ros-shadow-fixed 26th Feb.
> - Kobuki and Turtlebot sourceshttp://ros.org/wiki/turtlebot/Tutorials/groovy/Source%20Installation(these should match the current debs in ros-shadow-fixed).
> 
> I'm running in different shells:
> 
> > roslaunch turtlebot_bringup minimal.launch
> > roslaunch turtlebot_bringup 3dsensor.launch
> > roslaunch turtlebot_rviz_launchers view_robot.launch
> 
> And in rviz, I can enable and view the depth registered 3d image, the
> point cloud registered image and also the laser scan.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/turtlebot/turtlebot/issues/57#issuecomment-14160380
> .

## 

Manager of Robot Development
Willow Garage
68 Willow Rd.
Menlo Park, Ca 94025

**Comment by corot** [comment] 2013-03-06 02:36
Any progress on this? ros-groovy-depthimage-to-laserscan was updated yesterday, I think.

Can you retry after upgrading your system?  We are puzzled with this issue.... sorry.

**Comment by stonier** [comment] 2013-03-06 03:10
I wanted to go back and test those older versions of debs here, but Tully pushed shadow fixed to public, so not really convenient right now.

Another thing that might be relevant - it might be due to the laptop itself?

Anyway, can't reproduce here. Let us know if it is a continuing problem, otherwise we'll close this issue shortly.

**Comment by chadrockey** [comment] 2013-03-06 04:10
As far as I know, depthimage_to_laserscan hasn't changed recently.

I did some googling and people found issues with kinects and depth registered that can cause it to output entirely black images.  I turn these into NaNs since they are invalid data.

Looks like upgrading packages is the fix.

http://answers.ros.org/question/53706/registered-depth-image-is-black/

http://answers.ros.org/question/55513/roboearth-scanning-issues/

**Comment by mmwise** [comment] 2013-03-06 10:08
we can close the ticket for now, I'll update to the current release and
test it in the next couple days

**Closed as completed** 2013-03-06 14:10 UTC
