### ISSUE TITLE
3dsensor.launch depth_registered/points does not have rgb field

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#55] opened 2013-02-12 08:17 UTC
not sure it is supposed to be.

**Comment by jihoonl** [comment] 2013-02-13 01:24
Fixed.  e214479f3128ae32fce69f4aa9d693251fd3b349

**Comment by stonier** [comment] 2013-02-13 02:42
Jihoon, 3d sensor by design, is such that you can turn off processing if you need to.

After that fix, it will always be publishing point clouds. It's not necessary for some applications, like navigation.

Also, it was publishing registered depth clouds, just not in point cloud format. We should perhaps make that an option in arg form.

**Comment by jihoonl** [comment] 2013-02-13 02:56
I thought we decided to provide full data by the default but provide a way to disable the things for advanced users.

Previously, it already has depth_registered/points but just xyz. which is not proper. Just as openni_launch does, we should provide xyzrgb data with depth_registration:=true, and only xyz with depth_registration:=false.

I have checked Depth Cloud but it is just sensor_msgs/Image so we should provide it for user convenience..

**Comment by jihoonl** [comment] 2013-02-13 02:57
also for object recognition purpose, it is worth to have.

**Comment by jihoonl** [comment] 2013-02-13 03:54
Maybe I am mis-understanding the concept of depth cloud. Shall we wait for someone-else's input?

**Comment by corot** [comment] 2013-02-13 08:45
We need to decide between a minimalist (as stated the header) and a full-data (current version) 3dsensor.launch.

I vote for the full-data version, as people will probably use 3dsensor.launch to play, visualize and test, while applications can disable all but the stuff they need. I imagine that a user launching 3dsensor will expect to see fancy RGB pointclouds

I think Jihoon's change makes sense: if you want RGB data in your pointcloud, almost surely you want it registered. If you just want XYZ pointcloud, there are nothing to register. If you don't need pointcloud at all, just set depth_processing to false.

**Comment by corot** [comment] 2013-02-13 08:47
Question: what means for a depth cloud to be "registered"? To my knowledge, depth clouds are just depth images, aren't it?

**Comment by stonier** [comment] 2013-02-13 15:28
In singapore and having a better look at the file in full context (shouldn't have hurried a view of only the commit this morning). You're spot on Jihoon, sorry for the confusion - closing.

Jorge, the registration puts the raw data from rgb and depth on the same frame of reference. Otherwise a raw data value of x_, y_, z\* in the depth frame doesn't associate with x_, y_, z\* in the rgb frame (offset of the depth/rgb camera locations). For the kinect, I believe this is done in software and the asus in hardware.

**Closed as completed by stonier** 2013-02-13 15:28 UTC
Labels: bug
