### ISSUE TITLE
Xtion Pro Broken

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot#33] opened 2012-11-26 05:02 UTC
Depth point clouds work, but registered depth point clouds fail.

ERROR: Unsupported encoding [yuv422]

**Comment by bit-pirate** [comment] 2012-12-09 05:51
I think that's link to the current OpenNi problems.

**Comment by jihoonl** [comment] 2013-01-01 23:57
/camera/rgb/image_raw, /camera/rgb/image_color are failing with the same error in rviz
ERROR: Unsupported encoding [yuv422]

**Comment by jihoonl** [comment] 2013-01-02 01:06
I have tried to investigate the issue to run other applications.

I have tried the belows and confirmed they work fine.
- Niviewer 
- rosrun image_view image_view image:=/camera/rgb/image_color 
- rosrun image_view image_view image:=/camera/rgb/image_raw
- subscribing /camera/depth/points in rviz 

But the belows are not working.
- subscribing /camera/depth_registered/points in rviz
  [ERROR] [1357088044.169821755]: Unsupported encoding [yuv422]
- subscribing /camera/rgb/image_mono in rviz
  OpenCV Error: Bad flag (parameter or structure field) (Unknown/unsupported color conversion code) in cvtColor, file /tmp/buildd/ros-groovy-opencv2-2.4.3-6precise-20130101-1424/modules/imgproc/src/color.cpp, line 3800
  terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/buildd/ros-groovy-opencv2-2.4.3-6precise-20130101-1424/modules/imgproc/src/color.cpp:3800: error: (-206) Unknown/unsupported color conversion code in function cvtColor

[camera_nodelet_manager-2] process has died [pid 17220, exit code -6, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/jihoonl/.ros/log/650fa3b4-5478-11e2-9054-3085a9948f5e/camera_nodelet_manager-2.log].
log file: /home/jihoonl/.ros/log/650fa3b4-5478-11e2-9054-3085a9948f5e/camera_nodelet_manager-2*.log

**Comment by stonier** [comment] 2013-01-02 05:09
**Xtion Pro Depth Registration**

```
roslaunch openni_launch openni.launch depth_registration:=true
```

Firing up rviz with the `Depthcloud` plugin:
- Depth Map Topic `/camera/depth_registered/points`
- Color Image Topic `/camera/rgb/image_color`
- Color Transform `RGB8`

The depth cloud works, but coloured pixels show up like an rgb scrambled egg (see encoding problem above).

**Comment by stonier** [comment] 2013-01-02 05:09
I'm not sure which issue trackers to hit for this problem - if anyone has any advice, it would be welcome.

**Comment by chadrockey** [comment] 2013-01-02 21:12
Looks like the problem is here:
https://github.com/ros-perception/image_pipeline/blob/master/image_proc/src/nodelets/debayer.cpp#L132

image_encodings.h returns true for YUV422 being "color".
https://github.com/ros/common_msgs/blob/master/sensor_msgs/include/sensor_msgs/image_encodings.h#L107

I suspect this can be fixed by reordering the if/else statements.  I've been in contact with @vrabaud and we're working on a fix.

The symptoms are that the yuv422 encoding is sent throughout the system, but only some programs can support that encoding.  RVIZ and the color pointcloud generator are having issues since they expect RGB8.

**Comment by vrabaud** [comment] 2013-01-03 15:31
I fixed the original bug and the "subscribing /camera/rgb/image_mono in rviz" from https://github.com/turtlebot/turtlebot/issues/33#issuecomment-11798355  in image_pipeline 1.10.0. Please download from shadow-fixed.
I could not reproduce the "Xtion Pro Depth Registration" from https://github.com/turtlebot/turtlebot/issues/33#issuecomment-11800374 . If that still happens with the latest version, please open up a ticket in https://github.com/ros-perception/image_pipeline/issues
Thx

**Comment by jihoonl** [comment] 2013-01-04 06:16
I would like to keep this open until all asus problem issues are solved as a check list.

**Comment by jihoonl** [comment] 2013-01-04 07:33
I have tried shadow-fixed version openni launch with ASUS X201E and got error below.

terminate called after throwing an instance of 'openni_wrapper::OpenNIException'
  what():  unsigned int openni_wrapper::OpenNIDriver::updateDeviceList() @ /tmp/buildd/ros-groovy-openni-camera-1.8.6/debian/ros-groovy-openni-camera/opt/ros/groovy/stacks/openni_camera/src/openni_driver.cpp @ 125 : enumerating image nodes failed. Reason: One or more of the following nodes could not be enumerated:

Image: PrimeSense/SensorV2/5.1.0.41: Failed to set USB interface!

[camera_nodelet_manager-2] process has died [pid 10379, exit code -6, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera_nodelet_manager-2.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera_nodelet_manager-2_.log
[FATAL] [1357284679.099316294]: Service call failed!
[FATAL] [1357284679.099697954]: Service call failed!
[FATAL] [1357284679.099830026]: Service call failed!
[FATAL] [1357284679.100184079]: Service call failed!
[FATAL] [1357284679.100533811]: Service call failed!
[FATAL] [1357284679.101371326]: Service call failed!
[camera/depth_registered/rectify_depth-13] process has died [pid 12344, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load image_proc/rectify /camera_nodelet_manager --no-bond image_mono:=image_raw image_rect:=image_rect_raw __name:=rectify_depth __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-rectify_depth-13.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-rectify_depth-13_.log
[camera/depth_registered/metric-15] process has died [pid 12427, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load depth_image_proc/convert_metric /camera_nodelet_manager --no-bond __name:=metric __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-metric-15.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-metric-15_.log
[camera/depth_registered/metric_rect-14] process has died [pid 12383, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load depth_image_proc/convert_metric /camera_nodelet_manager --no-bond image_raw:=image_rect_raw image:=image_rect __name:=metric_rect __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-metric_rect-14.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-depth_registered-metric_rect-14_.log
[camera/points_xyzrgb_depth_rgb-16] process has died [pid 12469, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb /camera_nodelet_manager --no-bond rgb/image_rect_color:=rgb/image_rect_color rgb/camera_info:=rgb/camera_info depth_registered/image_rect:=depth_registered/image_rect_raw depth_registered/points:=depth_registered/points __name:=points_xyzrgb_depth_rgb __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-points_xyzrgb_depth_rgb-16.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-points_xyzrgb_depth_rgb-16_.log
[camera/disparity_depth-17] process has died [pid 12513, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load depth_image_proc/disparity /camera_nodelet_manager --no-bond left/image_rect:=depth/image_rect_raw right:=projector left/disparity:=depth/disparity __name:=disparity_depth __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-disparity_depth-17.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-disparity_depth-17_.log
[camera/disparity_depth_registered-18] process has died [pid 12559, exit code 255, cmd /opt/ros/groovy/lib/nodelet/nodelet load depth_image_proc/disparity /camera_nodelet_manager --no-bond left/image_rect:=depth_registered/image_rect_raw right:=projector left/disparity:=depth_registered/disparity __name:=disparity_depth_registered __log:=/home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-disparity_depth_registered-18.log].
log file: /home/yujin/.ros/log/a3a7ca74-5640-11e2-a639-20689df5aa4b/camera-disparity_depth_registered-18*.log

**Comment by jihoonl** [comment] 2013-01-04 07:48
While testing ASUS X201e with Kinect, I got this error too.

terminate called after throwing an instance of 'cv_bridge::Exception'
  what():  Unsupported conversion from [bayer_grbg8] to [mono8]
[camera_nodelet_manager-2] process has died [pid 17809, exit code -6, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/yujin/.ros/log/df75ffe2-5642-11e2-ac29-20689df5aa4b/camera_nodelet_manager-2.log].
log file: /home/yujin/.ros/log/df75ffe2-5642-11e2-ac29-20689df5aa4b/camera_nodelet_manager-2*.log

**Comment by vrabaud** [comment] 2013-01-04 08:48
Please specify the version you are using. it seems you are using 1.10.0 of image_pipeline, I actually pushed 1.10.1 that fixes your last issue. Please confirm that https://github.com/turtlebot/turtlebot/issues/33#issuecomment-11874813 is fixed .
Concerning https://github.com/turtlebot/turtlebot/issues/33#issuecomment-11874581 it is a pure driver error. I get those when connecting to a USB3 port which is not supported by the driver. You just do a "roslaunch openni_launch openni.launch" right ?

**Comment by jihoonl** [comment] 2013-01-04 08:59
@vrabaud  

Yea I confirmed that "image_mono" works with 1.10.0. Thanks! 

I am not sure if "Failed to set USB interface!" error is caused by USB 3.0 port though. I have tried Kinect and Asus both and found that Kinect was working properly.

I will test 1.10.1 version with both Kinect and Asus next Monday and let you know the status.

**Comment by vrabaud** [comment] 2013-01-04 09:11
BTW, my bad, you Bayer to Mono conversion got fixed in vision_opencv 1.10.0 (that has nothing to do with image_pipeline). image_pipeline 1.10.1 was just a patch on a regression I brough in 1.10.0 to fix the original issue :)

The error that's typical with USB3 is:

process[camera_base_link3-22]: started with pid [8129]
[ERROR] [1357290558.923855107]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressedDepth/set_parameters]
[ERROR] [1357290559.055822055]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/compressed/set_parameters]
[ERROR] [1357290559.274509346]: Tried to advertise a service that is already advertised in this node [/camera/depth_registered/image_rect_raw/theora/set_parameters]
terminate called after throwing an instance of 'openni_wrapper::OpenNIException'
  what():  unsigned int openni_wrapper::OpenNIDriver::updateDeviceList() @ /tmp/buildd/ros-groovy-openni-camera-1.8.6/debian/ros-groovy-openni-camera/opt/ros/groovy/stacks/openni_camera/src/openni_driver.cpp @ 125 : enumerating image nodes failed. Reason: One or more of the following nodes could not be enumerated:

Image: PrimeSense/SensorV2/5.1.0.41: Failed to set USB interface!

[camera_nodelet_manager-2] process has died [pid 6866, exit code -6, cmd /opt/ros/groovy/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/home/vrabaud/.ros/log/65485826-564e-11e2-83a6-6427374cdcdb/camera_nodelet_manager-2.log].
log file: /home/vrabaud/.ros/log/65485826-564e-11e2-83a6-6427374cdcdb/camera_nodelet_manager-2*.log

(I get that with my with ASUS Xtion pro)

How do you generate that error ? just "roslaunch openni_launch openni.launch" right ?

**Comment by jihoonl** [comment] 2013-01-04 09:18
@vrabaud 

ahhhh... I was so stupid. I just realized I was testing with two USB3.0 ports...  :(. My bad.
Yeah I did "roslaunch openni_launch openni.launch"

BTW,

I have tried 

rosrun image_view image_view image:=/camera/rgb/image_color
rosrun image_view image_view image:=/camera/rgb/image_mono
rosrun image_view image_view image:=/camera/rgb/image_raw

and found that only image_color is not being streamed. will 1.10.1 fix this?

**Comment by vrabaud** [comment] 2013-01-04 09:20
Yop, it will :) My regression was basically that YUV422 was published on mono at the same time as mono ... how clever. Hence some flickering on mono and no color on color

**Comment by jihoonl** [comment] 2013-01-04 09:25
ahh haha it happens.  :)

I will test stuffs on Monday with the newest version of code and post the results. Thanks Vincent!

**Comment by chadrockey** [comment] 2013-01-05 00:39
It all looks good here.  We had another small issue with catkinized openni_camera and openni_launch leaking into the release, but that has been fixed.
https://github.com/ros-drivers/openni_camera/commit/db77f637d2b45dd0678867cfe7940ac920113fd3

From shadow-fixed right now, I see colorized pointclouds from both the Kinect and the Xtion.  :)

**Comment by jihoonl** [comment] 2013-01-07 01:21
@vrabaud  I have tested ASUS depth_registraion, image_color, image_rect_color and etcs

it works!! Yay XD Thanks!

**Closed as completed by jihoonl** 2013-01-07 01:21 UTC
Labels: bug
