### ISSUE TITLE
kinect stability

### ISSUE THREAD

**Issue by jihoonl** [turtlebot/turtlebot#107] opened 2013-10-25 07:19 UTC
In some laptops, kinect driver really often crashes.

**Comment by stonier** [comment] 2013-10-25 07:35
Needs more than this to start debugging. A copy/paste of the error would be useful.

**Comment by stonier** [comment] 2013-10-27 23:47
Are people on ros answers experiencing the same problems?

I'd like to confirm that there is actually a problem first. Working with no data here.

**Comment by stonier** [comment] 2013-11-24 11:30
@corot and @bit-pirate did alot of testing and couldn't reproduce any issues on multiple robots.

I also ploughed through ros answers and came up with nothing recent.

Closing.

**Comment by tfoote** [comment] 2013-11-25 00:39
Is this an issue with Kinects that basically won't start streaming? I can
reproduce that and the last few demos I've switched to the freenect driver
at 2am to make sure follower worked.

**Comment by bit-pirate** [comment] 2013-11-25 01:15
> Is this an issue with Kinects that basically won't start streaming?

I can't remember similar issues. Could you provide some information about how to reproduce this? Please also include your laptop's type and model number. Also, did you make sure not to use a USB3.0 port? We had issues with Kinects on USB3.0 in the past.

**Comment by tfoote** [comment] 2013-11-25 02:12
The ones we have are the ones provided with the bots.  And we were definitely not plugging into the USB 3.0. I'm traveling this week. @wjwoodward had the same issues and is near the devices so might be able to help provide more details. I'll be back next week.

**Comment by pvandervorst** [comment] 2013-12-04 14:42
I have support tickets coming in with Kinect not working after running dist-upgrade. I believe it works fine on 12.04, but anything later and the Kinect won't stream any data.

**Comment by stonier** [comment] 2013-12-04 14:46
Ah, that might explain why I haven't seen it - have only worked with precise + turtlebot.

**Comment by stonier** [comment] 2014-06-01 04:18
Working fine on 14.04 and haven't had any news on this for a while so I'll close this. Reopen with a new ticket if there are fresh problems.

**Closed as completed by stonier** 2014-06-01 04:18 UTC
